# Generated by Django 3.2.7 on 2021-09-14 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='status',
        ),
    ]
